import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/linik-sans" rel="stylesheet" />
      </head>
      <body
        className="antialiased"
      >
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
